apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsassignment-2-app-green-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: jayaram059/python-demoapp:v2
          ports:
            - containerPort: 5050
